### ISSUE TITLE
support for dist files / overwriting

### ISSUE THREAD

**Issue by rauwebieten** [samrap/gestalt-docs#1]
Usually I have a dist file (which is added to my git project), and local configuration files (not in git).
I'd like to load dist filesfirst, and then overwrite them with local configuration files.

For example:

app.dist.ini
´´´
db.hostname = myhostname
db.database = mydatabase
db.username = ...
´´´

and then in app.ini
´´´
db.hostname = mysql.host.com
db.database = somerealdbname
db.username = ...
´´´

Is this possible out of the box?
Or should I create my own loaders?

**Comment by samrap** [comment]
Linking to the active issue: https://github.com/samrap/gestalt/issues/24
